### ISSUE TITLE
RegisterHook problems

### ISSUE THREAD

**Issue by DeadMor0z** [UE4SS/UE4SS#7]
Are there any limitation on hooked function type/parameters?
I'm trying to hook on function with signature `void ServerRenameStorage(AStorage* Storage, const FString& NewName)` and when callback is trying to execute I'm gheting following error:
```
Error executing hooked function /Script/Maine.SurvivalPlayerController:ServerRenameStorage: [push_strproperty] Operation::GetParam is not supported
```

**Comment by UE4SS** [comment]
There are some limitations due to my priorities.
I prioritize what's needed when it's needed and so far no one's needed this particular feature.

I will look into this restriction, and as with your other question, I recommend that you add me on discord (check your other issue for my discord name) to avoid further delays.
