### ISSUE TITLE
xinput1_3.dll injector doesn't work with WinGDK version of Grounded

### ISSUE THREAD

**Issue by olegbl** [UE4SS/UE4SS#8]
The xinput1_3.dll injector does not seem to work with WinGDK binaries (i.e. Xbox Game Pass version of game). UE4SS.log doesn't get created, so not much debug info available.

Injecting ue4ss.dll manually (e.g. via Universal UE4 Unlocker) works fine. UE4SS.log: [https://pastebin.com/E09AKcms](https://pastebin.com/E09AKcms)

Renaming "xinput1_3.dll" to "xinput1_4.dll" makes the auto-injector work. UE4SS.log: [https://pastebin.com/zfZ8X8DQ](https://pastebin.com/zfZ8X8DQ)

Users with the Win64 version of the game seem to be fine using "xinput1_3.dll" though, so unsure why the two versions would use a different version of XInput.

Also not sure if using the wrong version of the DLL would cause any issues (I'm assuming yes, but I haven't actually noticed any).

**Comment by UE4SS** [comment]
The `xinput1_3` dll that comes with UE4SS will try to load `xinput1_3.dll` from your system directory.
That means that it could be problematic if there are API or ABI differences between xinput1_3 and xinput1_4 because the game will expect xinput1_4 but your supplying xinput1_3.

Also, if you're using the mods from `TheLich` on nexus, you need to use the dll that they include because it's a custom version that is compatible with stock UE4SS 1.3.
